name: AI-Writer-On-Action
on:
  workflow_dispatch:
jobs:
  OCR:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "准备conda环境"
        run: |
          sudo rm -rf /usr/bin/conda
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -n writer python=3.8.13 pip pandas=1.5.1 numpy=1.23.4
      - name: "准备模型文件"
        run: |
          #cd models
          #aria2c -x10 "https://github.com/LemonFan-maker/Download-Models/releases/download/%E7%BB%BC%E5%90%88%E8%A8%80%E6%83%85%26%E7%8E%84%E5%B9%BB%26%E5%8F%A4%E4%BB%A3%E8%A8%80%E6%83%85%26%E9%87%8D%E7%94%9F(AI-Writer)/Ancient.h5" "https://github.com/LemonFan-maker/Download-Models/releases/download/%E7%BB%BC%E5%90%88%E8%A8%80%E6%83%85%26%E7%8E%84%E5%B9%BB%26%E5%8F%A4%E4%BB%A3%E8%A8%80%E6%83%85%26%E9%87%8D%E7%94%9F(AI-Writer)/comp.romance.h5" "https://github.com/LemonFan-maker/Download-Models/releases/download/%E7%BB%BC%E5%90%88%E8%A8%80%E6%83%85%26%E7%8E%84%E5%B9%BB%26%E5%8F%A4%E4%BB%A3%E8%A8%80%E6%83%85%26%E9%87%8D%E7%94%9F(AI-Writer)/Mysterious.h5" "https://github.com/LemonFan-maker/Download-Models/releases/download/%E7%BB%BC%E5%90%88%E8%A8%80%E6%83%85%26%E7%8E%84%E5%B9%BB%26%E5%8F%A4%E4%BB%A3%E8%A8%80%E6%83%85%26%E9%87%8D%E7%94%9F(AI-Writer)/Reborn.h5"
      - name: "安装依赖"
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate writer
          pip install -r requirements.txt
      - name: "安装内网穿透服务"
        run: |
          aria2c https://github.com/cloudflare/cloudflared/releases/download/2022.12.1/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
      - name: "启动续写服务"
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate writer
          sudo sysctl -w net.core.rmem_max=250000
          nohup streamlit run webui.py & \
          cloudflared tunnel --url $(hostname -I)
